version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: apollo-server
    versions:
    - 2.19.2
    - 2.20.0
    - 2.21.0
    - 2.21.1
    - 2.21.2
    - 2.22.1
    - 2.22.2
  - dependency-name: apollo-server-express
    versions:
    - 2.19.2
    - 2.20.0
    - 2.21.0
    - 2.21.1
    - 2.21.2
    - 2.22.1
    - 2.22.2
  - dependency-name: apollo-datasource-rest
    versions:
    - 0.10.0
    - 0.11.0
    - 0.9.7
  - dependency-name: lodash
    versions:
    - 4.17.20
