version: '3'

services:
  server:
    container_name: node
    image: pljarlegan/apollo-server-marvel:1.0.0
    restart: always
    ports:
      - 4000:4000
    env_file: .env
    environment:
      - NODE_ENV="production"
    stop_grace_period: 1s


